/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MrE_Sauce (https://sketchfab.com/MrE_Sauce)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-tiny-toy-tank-d9460c43a15e4ab8816517ca11b41f98
Title: Cartoon Tiny Toy Tank
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		pCube1_yellow_grey_0: THREE.Mesh;
		pCube2_treds_0: THREE.Mesh;
		pCylinder4_yellow_grey_0: THREE.Mesh;
		pCylinder4_black_0: THREE.Mesh;
		pCylinder5_yellow_grey_0: THREE.Mesh;
		pCylinder5_black_0: THREE.Mesh;
		pCylinder6_yellow_grey_0: THREE.Mesh;
		pCylinder6_black_0: THREE.Mesh;
		pCylinder7_yellow_grey_0: THREE.Mesh;
		pCylinder7_black_0: THREE.Mesh;
		pCylinder8_yellow_grey_0: THREE.Mesh;
		pCylinder8_black_0: THREE.Mesh;
		pCylinder9_yellow_grey_0: THREE.Mesh;
		pCylinder9_black_0: THREE.Mesh;
		pCube4_yellow_grey_0: THREE.Mesh;
		pCube5_lambert11_0: THREE.Mesh;
		pCube5_lambert9_0: THREE.Mesh;
		pCube6_lambert9_0: THREE.Mesh;
		pCube7_lambert11_0: THREE.Mesh;
		pCube7_lambert9_0: THREE.Mesh;
		pCube8_black_0: THREE.Mesh;
		pCylinder22_yellow_grey_0: THREE.Mesh;
		pCylinder22_black_0: THREE.Mesh;
		pCylinder23_yellow_grey_0: THREE.Mesh;
		pCylinder23_black_0: THREE.Mesh;
		pCylinder24_yellow_grey_0: THREE.Mesh;
		pCylinder24_black_0: THREE.Mesh;
		pCylinder25_yellow_grey_0: THREE.Mesh;
		pCylinder25_black_0: THREE.Mesh;
		pCube9_treds_0: THREE.Mesh;
		pCylinder32_yellow_grey_0: THREE.Mesh;
		pCylinder32_black_0: THREE.Mesh;
		pCylinder33_yellow_grey_0: THREE.Mesh;
		pCylinder33_black_0: THREE.Mesh;
		pCube10_black_0: THREE.Mesh;
		pCube11_black_0: THREE.Mesh;
		pCylinder2_yellow_grey_0: THREE.Mesh;
		pCube12_black_0: THREE.Mesh;
		pCylinder34_black_0: THREE.Mesh;
		pCube13_black_0: THREE.Mesh;
		pCube14_black_0: THREE.Mesh;
		pCube15_black_0: THREE.Mesh;
	};
	materials: {
		yellow_grey: THREE.MeshStandardMaterial;
		treds: THREE.MeshStandardMaterial;
		black: THREE.MeshStandardMaterial;
		lambert11: THREE.MeshStandardMaterial;
		lambert9: THREE.MeshStandardMaterial;
	};
};

export function CharacterTank(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("models/tank.glb") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group
				position={[2.818, 0.954, 3.776]}
				rotation={[0.374, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder4_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder4_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[2.818, 0.013, 2.508]}
				rotation={[0.411, 0, -Math.PI / 2]}
				scale={[0.834, 0.6, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder5_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder5_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[2.818, 0.013, 0.919]}
				rotation={[-0.343, 0, -Math.PI / 2]}
				scale={[0.834, 0.6, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder6_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder6_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[2.818, 0.004, -0.689]}
				rotation={[1.359, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder7_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder7_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[2.818, 0.004, -2.288]}
				rotation={[-2.628, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder8_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder8_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[2.818, 0.22, -3.868]}
				rotation={[0.362, 0, -Math.PI / 2]}
				scale={[0.834, 0.6, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder9_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder9_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group position={[-1.427, 2.339, 4.508]} scale={0.692}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCube5_lambert11_0.geometry}
					material={materials.lambert11}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCube5_lambert9_0.geometry}
					material={materials.lambert9}
				/>
			</group>
			<group position={[1.427, 2.339, 4.508]} scale={0.692}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCube7_lambert11_0.geometry}
					material={materials.lambert11}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCube7_lambert9_0.geometry}
					material={materials.lambert9}
				/>
			</group>
			<group
				position={[-2.827, 0.013, 0.919]}
				rotation={[-0.343, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder22_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder22_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[-2.827, 0.013, 2.508]}
				rotation={[0.411, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder23_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder23_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[-2.827, 0.22, -3.868]}
				rotation={[0.362, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder24_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder24_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[-2.827, 0.004, -2.288]}
				rotation={[-2.628, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder25_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder25_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[-2.827, 0.004, -0.689]}
				rotation={[1.359, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder32_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder32_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<group
				position={[-2.827, 0.954, 3.776]}
				rotation={[0.374, 0, -Math.PI / 2]}
				scale={[0.834, 0.562, 0.834]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder33_yellow_grey_0.geometry}
					material={materials.yellow_grey}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.pCylinder33_black_0.geometry}
					material={materials.black}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube1_yellow_grey_0.geometry}
				material={materials.yellow_grey}
				position={[0, 1.566, 0]}
				scale={[4.654, 2.02, 8.729]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube2_treds_0.geometry}
				material={materials.treds}
				position={[2.827, 0.256, 0]}
				scale={[1, 2.011, 10.3]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube4_yellow_grey_0.geometry}
				material={materials.yellow_grey}
				position={[0, 3.701, -1.883]}
				rotation={[-0.076, 0, 0]}
				scale={[4.279, 3.293, 4.476]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube6_lambert9_0.geometry}
				material={materials.lambert9}
				position={[1.253, 2.464, 2.199]}
				rotation={[-0.113, 0, 0]}
				scale={[1.395, 0.161, 1.818]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube8_black_0.geometry}
				material={materials.black}
				position={[2.827, 0.256, 0]}
				scale={[1.035, 2.061, 10.556]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube9_treds_0.geometry}
				material={materials.treds}
				position={[-2.827, 0.256, 0]}
				scale={[1, 2.011, 10.3]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube10_black_0.geometry}
				material={materials.black}
				position={[-2.827, 0.256, 0]}
				scale={[1.035, 2.061, 10.556]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube11_black_0.geometry}
				material={materials.black}
				position={[0, 1.566, 0]}
				scale={[4.758, 2.256, 8.973]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCylinder2_yellow_grey_0.geometry}
				material={materials.yellow_grey}
				position={[0, 3.49, 1.408]}
				rotation={[-1.779, 0, 0]}
				scale={[0.282, 2.085, 0.282]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube12_black_0.geometry}
				material={materials.black}
				position={[0, 3.815, -1.892]}
				rotation={[-0.076, 0, 0]}
				scale={[4.573, 3.519, 4.783]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCylinder34_black_0.geometry}
				material={materials.black}
				position={[0, 3.474, 1.476]}
				rotation={[-1.779, 0, 0]}
				scale={[0.345, 2.13, 0.345]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube13_black_0.geometry}
				material={materials.black}
				position={[1.427, 2.339, 4.508]}
				scale={0.795}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube14_black_0.geometry}
				material={materials.black}
				position={[-1.427, 2.339, 4.508]}
				scale={0.795}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.pCube15_black_0.geometry}
				material={materials.black}
				position={[1.253, 2.554, 2.199]}
				rotation={[-0.113, 0, 0]}
				scale={[1.534, 0.173, 2]}
			/>
		</group>
	);
}

useGLTF.preload("models/tank.glb");
